site_name: Celeritas
site_url: http://docs.celeritas.localhost

theme:
  name: material
  palette:
    scheme: slate
    primary: deep orange
    accent: orange
  features:
    - navigation.tabs
    - navigation.sections
    - search.suggest
    - search.highlight

markdown_extensions:
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [/app/src]

nav:
  - Home: index.md
  - Getting Started: setup.md
  - Usage Guide: usage.md
  - Configuration: config.md
  - API Reference: api.md
