name: CI

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build Dev Container
      run: make build-dev
    - name: Run Linters
      run: make lint
    - name: Run Tests
      run: make test
